name       : perl-datetime-format-strptime
version    : 1.73
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.73.tar.gz : 6d077806eb8581e5f28ffaff0bd2bb7a15114f9e745f61bd519405047765b2be
license    : Artistic-2.0
component  : programming.perl
summary    : Parse and format strp and strf time patterns
description: |
    Parse and format strp and strf time patterns
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
