name       : perl-datetime-format-strptime
version    : '1.75'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.75.tar.gz : 4fcfb2ac4f79d7ff2855a405f39050d2ea691ee098ce54ede8af79c8d6ab3c19
license    : Artistic-2.0
component  : programming.perl
summary    : Parse and format strp and strf time patterns
description: |
    Parse and format strp and strf time patterns
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-package-stash
    - perl-params-util
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
    - perl-variable-magic
rundeps    :
    - perl-datetime
    - perl-package-deprecationmanager
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
